version: '3'

services:
  mysql-dev:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: rootadm
      MYSQL_DATABASE: spring-security
    ports:
      - "3308:3306"


#  client:
#    image: mysql:8.0.32
#    depends_on:
#      - mysql-dev
#    command: mysql -uroot -prootadm -hmysql-dev spring-security

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080